import { jsPDF } from 'jspdf'

export const generatePDF = (assessmentData) => {
  const doc = new jsPDF()
  
  // Colors - updated to use #10264c for headers and titles, #86a6e5 for subtitle and URL
  const darkBlue = [16, 38, 76]      // #10264c - Primary blue for headers and titles
  const lightBlue = [134, 166, 229]  // #86a6e5 - Light blue for subtitle and URL
  const textColor = [44, 62, 80]     // Dark gray for text
  const lightGray = [128, 128, 128]  // Light gray for secondary text
  const borderGray = [200, 200, 200] // Light gray for borders
  
  let yPosition = 0
  let currentPage = 1
  
  // Helper function to add header
  const addHeader = (isFirstPage = false) => {
    if (isFirstPage) {
      // Full header for first page - 25% bigger
      doc.setFillColor(...darkBlue)
      doc.rect(0, 0, 210, 44, 'F') // Increased from 35 to 44 (25% bigger)
      
      // Header text - aligned with main page title and subheadings
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(35) // Increased from 28
      doc.setFont('helvetica', 'bold')
      doc.text('EthiCheck', 20, 22) // Aligned with main page content at x=20
      
      // Subtitle in new light blue color - positioned to align bottom with description text
      doc.setTextColor(...lightBlue) // Changed to light blue #86a6e5
      doc.setFontSize(15) // Increased from 12
      doc.setFont('helvetica', 'normal')
      doc.text('The AI Ethics Assessment Platform', 20, 36) // Moved down and aligned with content
      
      // Right side text - properly aligned, moved further left, and updated colors
      doc.setTextColor(...lightBlue) // URL in light blue #86a6e5
      doc.setFontSize(13) // Increased from 12 to 13 as requested
      doc.text('www.ethicheck.ai', 125, 18) // Moved further left from 135 to 125
      doc.setTextColor(255, 255, 255) // Description text back to white
      doc.setFontSize(9) // Made smaller (was 10, now 9)
      doc.text('A free tool to support educators and', 125, 28) // Reduced line spacing
      doc.text('other professionals as they navigate AI Ethics', 125, 36) // Aligned bottom with subtitle
      
      return 54 // Increased from 45
    } else {
      // Thin header for subsequent pages - unchanged
      doc.setFillColor(...darkBlue)
      doc.rect(0, 0, 210, 15, 'F')
      
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.text('EthiCheck', 15, 10) // Moved right from 20 to 15 for consistency
      
      doc.setTextColor(...lightBlue) // Changed to light blue #86a6e5
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.text('www.ethicheck.ai', 160, 10)
      
      return 25
    }
  }
  
  // Helper function to add footer
  const addFooter = (pageNum, totalPages) => {
    // Simple blue footer band
    doc.setFillColor(...darkBlue)
    doc.rect(0, 285, 210, 12, 'F')
    
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(8)
    // Left side: Generated by EthiCheck • date
    doc.text(`Generated by EthiCheck • ${new Date().toLocaleDateString()}`, 15, 292) // Moved right from 20 to 15
    // Right side: Page numbering
    doc.text(`Page ${pageNum} of ${totalPages}`, 170, 292)
  }
  
  // Helper function to check if we need a new page
  const checkNewPage = (requiredSpace) => {
    if (yPosition + requiredSpace > 270) {
      addFooter(currentPage, 'X')
      doc.addPage()
      currentPage++
      yPosition = addHeader(false)
      yPosition += 10
    }
  }
  
  // Helper function to add section divider
  const addSectionDivider = () => {
    doc.setDrawColor(...borderGray)
    doc.setLineWidth(0.5)
    doc.line(20, yPosition, 190, yPosition)
    yPosition += 10
  }
  
  // Page 1 - Title and Project Info
  yPosition = addHeader(true)
  yPosition += 5 // Add extra space between header and title
  
  // Report title - now using the new blue color
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('AI Ethics Assessment Report', 20, yPosition)
  yPosition += 20
  
  // Executive Summary Section
  doc.setFontSize(18) // Bigger subheading
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.text('Executive Summary', 20, yPosition)
  yPosition += 10
  
  // Executive Summary content
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...textColor) // Reset to normal text color for content
  const overallGrade = assessmentData.overallGrade || 'B+'
  const riskLevel = assessmentData.riskLevel || 'Medium'
  
  const summaryText = `This comprehensive AI ethics assessment evaluates your ${assessmentData.projectTitle || 'AI project'} across six critical dimensions. The overall assessment grade is ${overallGrade} with a ${riskLevel.toLowerCase()} risk profile. This report provides detailed analysis, recommendations, and next steps to ensure ethical AI implementation aligned with current best practices and regulatory requirements.`
  
  const summaryLines = doc.splitTextToSize(summaryText, 170)
  doc.text(summaryLines, 20, yPosition)
  yPosition += summaryLines.length * 5 + 10
  
  addSectionDivider()
  
  // Project Information Section
  doc.setFontSize(18) // Bigger subheading
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.text('Project Information', 20, yPosition)
  yPosition += 10
  
  // Project Information content - including generation date
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...textColor) // Reset to normal text color for content
  
  const projectInfo = [
    ['Project Title:', assessmentData.projectTitle || 'Not specified'],
    ['AI Tool/Platform:', assessmentData.aiTool || 'Not specified'],
    ['Organization Type:', assessmentData.organizationType || 'Not specified'],
    ['Primary Users:', assessmentData.userAge || 'Not specified'],
    ['Geographic Region:', assessmentData.country || 'Not specified'],
    ['Users Impacted:', assessmentData.usersImpacted || 'Not specified'],
    ['Report Generated:', new Date().toLocaleDateString()] // Moved here from top
  ]
  
  projectInfo.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold')
    doc.text(label, 20, yPosition)
    doc.setFont('helvetica', 'normal')
    doc.text(value, 80, yPosition)
    yPosition += 6
  })
  
  yPosition += 5
  addSectionDivider()
  
  // Project Description Section
  doc.setFontSize(18) // Bigger subheading
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.text('Project Description', 20, yPosition)
  yPosition += 10
  
  // Project Description content
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...textColor) // Reset to normal text color for content
  const description = assessmentData.description || 'No description provided.'
  const descriptionLines = doc.splitTextToSize(description, 170)
  doc.text(descriptionLines, 20, yPosition)
  yPosition += descriptionLines.length * 5 + 10
  
  // Page 2 - Assessment Results
  addFooter(currentPage, 'X')
  doc.addPage()
  currentPage++
  yPosition = addHeader(false)
  yPosition += 10
  
  // Individual Category Assessments Section
  doc.setFontSize(18) // Bigger subheading
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.text('Individual Category Assessments', 20, yPosition)
  yPosition += 15
  
  // Assessment Results Table
  const dimensions = assessmentData.scores || {}
  const dimensionNames = {
    'fairness': 'Fairness & Bias',
    'privacy': 'Privacy & Data Protection',
    'transparency': 'Transparency & Explainability',
    'autonomy': 'Human Oversight',
    'effectiveness': 'Organizational Effectiveness',
    'safety': 'Risk Management & Safety'
  }
  
  // Table header
  doc.setFillColor(240, 240, 240)
  doc.rect(20, yPosition, 170, 8, 'F')
  doc.setTextColor(...textColor)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('Category', 25, yPosition + 5)
  doc.text('Score', 120, yPosition + 5)
  doc.text('Grade', 140, yPosition + 5)
  doc.text('Risk Level', 165, yPosition + 5)
  yPosition += 8
  
  // Table rows
  doc.setFont('helvetica', 'normal')
  Object.entries(dimensions).forEach(([key, data]) => {
    const name = dimensionNames[key] || key
    const score = data.score || 0
    const grade = data.grade || 'N/A'
    const risk = data.riskLevel || 'Unknown'
    
    doc.setDrawColor(...borderGray)
    doc.line(20, yPosition, 190, yPosition)
    
    doc.text(name, 25, yPosition + 5)
    doc.text(score.toString(), 120, yPosition + 5)
    doc.text(grade, 140, yPosition + 5)
    doc.text(risk, 165, yPosition + 5)
    yPosition += 8
  })
  
  // Bottom border
  doc.line(20, yPosition, 190, yPosition)
  yPosition += 15
  
  addSectionDivider()
  
  // Key Findings Section
  doc.setFontSize(18) // Bigger subheading
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.text('Key Findings', 20, yPosition)
  yPosition += 10
  
  // Key Findings content
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...textColor) // Reset to normal text color for content
  
  const keyFindings = [
    `Overall Assessment Grade: ${overallGrade} - Your AI implementation demonstrates ${overallGrade === 'A' ? 'excellent' : overallGrade === 'B+' ? 'strong' : overallGrade === 'B' ? 'good' : 'adequate'} ethical practices.`,
    `Risk Profile: ${riskLevel} - This indicates ${riskLevel.toLowerCase() === 'low' ? 'minimal' : riskLevel.toLowerCase() === 'medium' ? 'moderate' : 'significant'} ethical concerns requiring attention.`,
    'Compliance Status: Your implementation shows good alignment with current AI ethics frameworks and regulatory requirements.',
    'Areas of Strength: Strong performance in data privacy and human oversight dimensions.',
    'Improvement Opportunities: Focus on bias transparency and impact assessment for enhanced ethical compliance.'
  ]
  
  keyFindings.forEach((finding, index) => {
    doc.text(`${index + 1}. `, 20, yPosition)
    const findingLines = doc.splitTextToSize(finding, 165)
    doc.text(findingLines, 28, yPosition)
    yPosition += findingLines.length * 5 + 3
  })
  
  // Page 3 - Recommendations and Next Steps
  addFooter(currentPage, 'X')
  doc.addPage()
  currentPage++
  yPosition = addHeader(false)
  yPosition += 10
  
  // Prioritized Recommendations Section
  doc.setFontSize(18) // Bigger subheading
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.text('Prioritized Recommendations', 20, yPosition)
  yPosition += 10
  
  // Prioritized Recommendations content
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...textColor) // Reset to normal text color for content
  
  const recommendations = [
    'Implement comprehensive bias testing protocols to ensure fair outcomes across all user demographics.',
    'Establish clear data governance policies with explicit consent mechanisms and data retention schedules.',
    'Develop transparent AI decision-making processes with clear explanation capabilities for end users.',
    'Create regular audit schedules to monitor AI performance and ethical compliance over time.',
    'Establish incident response procedures for addressing potential AI-related ethical concerns.'
  ]
  
  recommendations.forEach((rec, index) => {
    doc.setFont('helvetica', 'bold')
    doc.text(`${index + 1}. `, 20, yPosition)
    doc.setFont('helvetica', 'normal')
    const recLines = doc.splitTextToSize(rec, 165)
    doc.text(recLines, 28, yPosition)
    yPosition += recLines.length * 5 + 5
  })
  
  yPosition += 5
  addSectionDivider()
  
  // Next Steps Section
  doc.setFontSize(18) // Bigger subheading
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.text('Next Steps', 20, yPosition)
  yPosition += 10
  
  // Next Steps content
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...textColor) // Reset to normal text color for content
  
  const nextSteps = [
    'Review this assessment with your AI governance team and key stakeholders.',
    'Prioritize implementation of high-impact recommendations based on your organizational capacity.',
    'Establish timeline and assign responsibility for each recommended action item.',
    'Schedule follow-up assessment in 6-12 months to track progress and identify new considerations.',
    'Consider additional training for team members on AI ethics best practices and emerging regulations.'
  ]
  
  nextSteps.forEach((step, index) => {
    doc.setFont('helvetica', 'bold')
    doc.text(`${index + 1}. `, 20, yPosition)
    doc.setFont('helvetica', 'normal')
    const stepLines = doc.splitTextToSize(step, 165)
    doc.text(stepLines, 28, yPosition)
    yPosition += stepLines.length * 5 + 5
  })
  
  yPosition += 5
  addSectionDivider()
  
  // Disclaimer Section
  doc.setFontSize(18) // Bigger subheading
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkBlue) // Changed from textColor to darkBlue
  doc.text('Disclaimer', 20, yPosition)
  yPosition += 10
  
  // Disclaimer content
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...textColor) // Reset to normal text color for content
  doc.text('IMPORTANT DISCLAIMER', 20, yPosition)
  yPosition += 8
  
  doc.setFont('helvetica', 'normal')
  const disclaimerText = 'This assessment is provided by EthiCheck.ai as an guidance tool. While EthiCheck follows rigorous ethical frameworks and best practices, users must ensure that internal protocols are adhered to as per their institution\'s overall digital strategy and governance policies. This report does not constitute legal advice in any way. Organizations remain solely responsible for compliance with applicable laws, regulations, and institutional policies regarding AI implementation and data protection.'
  
  const disclaimerLines = doc.splitTextToSize(disclaimerText, 170)
  doc.text(disclaimerLines, 20, yPosition)
  yPosition += disclaimerLines.length * 5
  
  // Update all footers with correct page numbers
  const totalPages = currentPage
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addFooter(i, totalPages)
  }
  
  // Generate filename
  const timestamp = new Date().toISOString().split('T')[0]
  const projectName = (assessmentData.projectTitle || 'assessment').toLowerCase().replace(/[^a-z0-9]/g, '-')
  const filename = `ethicheck-assessment-${projectName}-${timestamp}.pdf`
  
  return {
    doc,
    filename
  }
}

export const downloadPDF = (assessmentData) => {
  const { doc, filename } = generatePDF(assessmentData)
  doc.save(filename)
}

export const printPDF = (assessmentData) => {
  const { doc } = generatePDF(assessmentData)
  doc.autoPrint()
  window.open(doc.output('bloburl'), '_blank')
}

